org.gradle.jvmargs=-Xmx480m
org.gradle.daemon=false
org.gradle.parallel=true
org.gradle.caching=true


minecraft_version=1.21.1
minecraft_version_range=[1.21.1]
neo_version=21.1.219
neo_version_range=[21.1.219,)
loader_version_range=[1,)

mod_id=bits_n_tracks
mod_name=Bits 'n' Tracks (Fork)
mod_license=GPL-3.0-only
mod_version=1.4.86-fork
mod_group_id=dev.qwxon.bitsntracks
mod_authors=qwxon, fork edits
mod_description=Create addon: flanged cogwheels with Sable physics for working tank tracks. Fork with tool modes, grip and track width controls.

create_version=6.0.10-280
ponder_version=1.0.82
flywheel_version=1.0.6
registrate_version=MC1.21-1.3.0+67
